### ISSUE TITLE
multiple textures for smooth terrain

### ISSUE THREAD

**Issue by blockspacer** [Relintai/broken_seals#1]
use a splat/texarray shader and then all you need is to populate the COLOR attributes of vertices with the material ID, which you use in shader

**Comment by Relintai** [comment]
Sorry I missed this for this long, I thought github would show newly opened issues at the front page.

I already thought of a different, but pretty much equivalent solution, jut haven't yet got to it.

I'm planning to use uv2 for this purpose, with COLOR.a to interpolate between uv1 and uv2. The gpu would need to sample the same texture twice, but the shader would only need to do a few more calculations. 

Also, this method only needs a few small changes, compared to texture arrays, which require serious modifications to everything, including COLOR, because I already use it for cheap baked lights and AO, and some dirt noise thing.

Thanks for bringing this up though, it made me think about, and realized that the uv2 thing can be implemented way simpler than I originally thought. It should be almost trivial to do.

(By the way, the voxel textures are already merged together automatically.)
